
name: Deploy to ECR

on:
  push:
    branches:
      - master

jobs:

  build:
    env:
        IMAGE: org/my-app

    name: Build Image
    runs-on: ubuntu-latest


    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"


      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get ECR password (temporary)
        id: get-ecr-password
        run: echo "::set-output name=password::$(aws ecr get-login-password)"


      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 566420885017.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: testjgq
          IMAGE_TAG: ${{ steps.prep.outputs.BUILD_ID }}

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
